JAVA-1948 Sessions should close properly when LBP fails to initialize.
apache/cassandra-java-driver pull request #1102
Opened 2018-10-03 15:15 UTC by GregBestland

2018-10-03 16:14 UTC, adutra requested changes

2018-10-03 16:14 UTC, adutra commented on integration-tests/src/test/java/com/datastax/oss/driver/api/core/ConnectIT.java
> +    while (size > 0 && System.currentTimeMillis() < maxTime) {
This is a very tight loop, you should at least sleep a little bit at each iteration. Or better yet, replace with:

``` 
    checkThat(() -> simulacronRule.cluster().getConnections().getConnections().isEmpty())
        .before(1, SECONDS)
        .becomesTrue();
```

2018-10-03 16:14 UTC, adutra commented on integration-tests/src/test/java/com/datastax/oss/driver/api/core/ConnectIT.java
> +  private static String provideNullString() {
Unused.

2018-10-03 16:14 UTC, adutra commented on integration-tests/src/test/java/com/datastax/oss/driver/api/core/ConnectIT.java
> +    } catch (DriverException e) {
Can you rename the exception to `ignored` to make IntelliJ happy? :)

2018-10-03 16:14 UTC, adutra commented on integration-tests/src/test/java/com/datastax/oss/driver/api/core/ConnectIT.java
> +  public void should_cleanup_on_lbp_init_failure() throws Exception {
Please add a little note in the javadocs of this method to link this test to JAVA-1948 for future reference.

2018-10-03 17:20 UTC, olim7t requested changes
👍 nice way to fix this.

+1 to Alexandre's comments about the tests.

Please also add a changelog entry, and follow existing conventions for the message: affirmative form, no "should", colon after the ticket number, and no period at the end. E.g. "JAVA-1948: Close session properly when LBP fails to initialize"

2018-10-05 22:16 UTC, olim7t approved these changes

2018-10-05 22:17 UTC, merged