JAVA-2090: Add support for additional_write_policy and read_repair ble options
apache/cassandra-java-driver pull request #1196
Opened 2019-02-22 15:55 UTC by emerkle826

2019-02-22 17:27 UTC, emerkle826 commented on integration-tests/src/test/java/com/datastax/oss/driver/api/core/metadata/TableOptionsIT.java
> +  // public static CustomCcmRule ccmRule = CustomCcmRule.builder().build();
Forgot to remove this after testing with it.

2019-02-28 07:41 UTC, tomekl007 approved these changes

2019-02-28 09:55 UTC, adutra approved these changes

2019-02-28 10:24 UTC, adutra submitted a review, later dismissed

2019-02-28 10:24 UTC, adutra commented on changelog/README.md
> +- [improvement] JAVA-2090: Add support for additional_write_policy and read_repair table options
Just noticed that the changelog entry is misplaced.

2019-03-07 18:20 UTC, olim7t requested changes

2019-03-07 18:20 UTC, olim7t commented on core/src/main/java/com/datastax/oss/driver/internal/core/metadata/schema/parsing/RelationParser.java
> +          .put("additional_write_policy", TypeCodecs.TEXT)
Nit: I moved the lines to respect alphabetical order. That way the output of `TableMetadata.describe()` will looks the same as CQLSH's `desc`.

2019-03-07 18:20 UTC, olim7t commented on integration-tests/src/test/java/com/datastax/oss/driver/api/core/metadata/TableOptionsIT.java
> +    assertThat(rs.wasApplied()).isTrue();
`wasApplied()` is for lightweight transactions only, it will always be true for a create statement.

2019-03-07 18:20 UTC, olim7t commented on integration-tests/src/test/java/com/datastax/oss/driver/api/core/metadata/TableOptionsIT.java
> +          .withKeyspace(false)
Why not let the rule create a keyspace? That way you don't need to do it in your test method.

2019-03-07 18:24 UTC, olim7t approved these changes

2019-03-07 18:31 UTC, merged