JAVA-3022 implementation of private link address translator
apache/cassandra-java-driver pull request #1597
Opened 2022-05-25 08:02 UTC by smiklosovic

2022-05-25 10:34 UTC, adutra requested changes
Thanks for the PR!

If this lands in the driver I'd also like to see reference.conf amended. Please modify the `advanced.address-translator` section and:

* Mention the new translator there;
* Add the new `advertised-hostname` option there (it should be commented out by default).

2022-05-25 10:34 UTC, adutra commented on core/src/main/java/com/datastax/oss/driver/internal/core/addresstranslation/PrivateLinkAddressTranslator.java
> +    LOG.debug(String.format("translating %s:%d to %s:%d", address, port, advertisedHostname, port));
You should avoid `String.format`:
```suggestion
    LOG.debug("Translating {}:{} to {}:{}", address, port, advertisedHostname, port));
```

2022-05-25 10:34 UTC, adutra commented on core/src/main/java/com/datastax/oss/driver/internal/core/addresstranslation/PrivateLinkAddressTranslator.java
> +  public static final DriverOption ADVERTISED_HOSTNAME_OPTION =
Since this is going to be part of the core driver, you should rather add this new option to `DefaultDriverOption`.

Then you should also declare a new `TypedDriverOption` so that folks using programmatic configuration can use the new option too.

2022-05-25 10:34 UTC, adutra commented on core/src/main/java/com/datastax/oss/driver/internal/core/addresstranslation/PrivateLinkAddressTranslator.java
> +public class PrivateLinkAddressTranslator implements AddressTranslator {
As discussed in the Jira ticket, you may want to give this a more generic name. Also, a bit of javadoc explaining why it is useful would be nice.

2022-05-25 12:15 UTC, smiklosovic commented
@adutra I fixed what I could, thanks for the review. This build will fail anyway on `MapBasedDriverConfigLoaderTest.should_fill_default_profile_like_reference_file:74` because I commented that property in reference config but it expects it is not commented? I am a little bit confused here. Would you please help me here?

2022-05-25 13:17 UTC, adutra submitted a review, later dismissed
I fixed your build issues, hope you don't mind. I will let @absurdfarce have a look and merge since he's the real boss ™️  now :-)

2022-05-25 13:38 UTC, adutra commented
> This build will fail anyway on MapBasedDriverConfigLoaderTest.should_fill_default_profile_like_reference_file:74 because I commented that property in reference config but it expects it is not commented? I am a little bit confused here. Would you please help me here?

This test is a special one that verifies that the programmatic configuration API would produce the exact same configuration as the file-based configuration API.

Since the option in reference.conf is commented out, it should not appear either in `OptionsMap.driverDefaults()`.

2022-06-22 09:52 UTC, smiklosovic commented
Hi @adutra , would you mind to fix the build once again? I am not sure what's wrong but "mvn clean install" fails again. I think I just force pushed something by accident and your changes are not there anymore.

2022-06-22 10:57 UTC, smiklosovic commented
Ok it seems I managed to build it.

2022-07-14 21:06 UTC, merged