JAVA-1328: Provide compatibility with Guava 20
apache/cassandra-java-driver pull request #784
Opened 2017-01-11 22:30 UTC by olim7t

Based on original work by @mspangdal.

2017-01-12 15:17 UTC, adutra commented
Is there a compelling reason to target 3.0.7 instead of 3.2.0? I would personally be more comfortable with 3.2.0.

2017-01-12 16:10 UTC, adutra requested changes

2017-01-12 16:10 UTC, adutra commented on driver-core/src/main/java/com/datastax/driver/core/GuavaCompatibility.java
> +    private static class Version18OrLower extends GuavaCompatibility {
Nit: adding `@SuppressWarnings("deprecation")` here would spare us a couple warnings.

2017-01-12 16:10 UTC, adutra commented on driver-core/src/main/java/com/datastax/driver/core/GuavaCompatibility.java
> +            Enumeration<URL> resources = Resources.class.getClassLoader()
`Resources` is itself part of Guava, and is marked `@Beta`. Why not use `GuavaCompatibility.class.getClassLoader()`?

2017-01-12 16:10 UTC, adutra commented on driver-core/src/main/java/com/datastax/driver/core/GuavaCompatibility.java
> +            return Futures.transform(input, function, executor);
Found one occurrence of this method in `com.datastax.driver.core.AsyncQueryTest#connectAndQuery`

2017-01-12 16:10 UTC, adutra commented on driver-core/src/main/java/com/datastax/driver/core/utils/MoreObjects.java
> +public class MoreObjects {
Since it's public, maybe we could add javadocs for methods in this class, even if I concede that their purposes are pretty obvious.

2017-01-12 16:10 UTC, adutra commented on driver-core/src/test/java/com/datastax/driver/core/policies/LimitingLoadBalancingPolicy.java
>  public class LimitingLoadBalancingPolicy extends DelegatingLoadBalancingPolicy {
The import `import com.google.common.collect.Sets` is unused.

2017-01-18 14:15 UTC, adutra commented
In addition to my review, we should also

1) in `/pom.xml`, replace the javadoc link with this one:

```
 <link>https://google.github.io/guava/releases/20.0/api/docs/</link>
```

2) Replace links to `code.google.com/p/guava-libraries` with `github.com/google/guava`; this happens in two files at least: `CloseFuture.java` and `ResultSetFuture.java`.

2017-01-18 18:03 UTC, olim7t commented on driver-core/src/main/java/com/datastax/driver/core/GuavaCompatibility.java
> +            Enumeration<URL> resources = Resources.class.getClassLoader()
I hadn't noticed it was beta. I think it's better to use a Guava class to make sure it's the classloader that loaded Guava, I've changed it to `Preconditions`.

2017-01-18 18:03 UTC, olim7t commented
Addressed all feedback.

2017-01-18 19:01 UTC, tolbertam commented
> Is there a compelling reason to target 3.0.7 instead of 3.2.0? I would personally be more comfortable with 3.2.0.

That's a good point, it doesn't break API compatibility, but is more of a new capability than a hotfix so 3.2.0 does seem more appropriate.

2017-01-18 20:40 UTC, tolbertam commented
CI looks happy with guava 16.0.1, 17.0, 18.0, 19.0, 20.0 and 21.0, excellent work!

2017-01-19 15:15 UTC, adutra approved these changes

2017-01-20 17:45 UTC, Xaerxess commented
Glad to see this approved! Is there any chance for a release in the near future?

2017-01-24 10:47 UTC, adutra commented
@Xaerxess no timeframe yet, but it shouldn't be long.

2017-02-09 11:46 UTC, adutra commented
Squashed and rebased on top of 3.x instead of 3.0.x.

2017-02-09 16:28 UTC, adutra commented
Note to reviewers: I added an extra commit to fix OSGi tests and also to revert the Import-Package instruction that we use to create our bundles. We need to explicitly declare that the driver bundle accepts any Guava version in the range [16.0.1,21) so I modified the instructions to read that.

2017-02-15 16:17 UTC, palaiya approved these changes

2017-02-16 10:40 UTC, merged