Fix version comparisons in tests
apache/cassandra-java-driver pull request #791
Opened 2017-01-25 15:44 UTC by adutra

Motivation:

@CassandraVersion and @DseVersion are not designed for tick-tock
releases and cannot understand versions such as “3.10”.

Modifications:

Redesign @CassandraVersion and @DseVersion to be able to fully accept
tick-tock releases and correctly compare them.
Additionally this commit adjusts log levels for Scassandra tests,
and prevents thrift from being enabled for C* >= 3.10.

Result:

@CassandraVersion and @DseVersion now can compare tick-tock releases
correctly.

2017-01-25 17:58 UTC, tolbertam commented on driver-core/src/test/java/com/datastax/driver/core/CCMBridge.java
> +                    (!dse && version.compareTo(VersionNumber.parse("3.10")) < 0)
I think C* 4.0 will be the first version without thrift.  It will still be present in 3.10, but not in trunk.

2017-01-25 18:00 UTC, tolbertam requested changes
Other than my comment about C* and Thrift, this looks good to me 👍

2017-01-26 13:22 UTC, tolbertam commented on driver-core/src/test/java/com/datastax/driver/core/CCMBridge.java
> +            return dse || version.compareTo(VersionNumber.parse("4.0")) < 0;
Just curious, but what is the significance of DSE here?  Although all versions of DSE support Thrift at the moment, i imagine that will change too.  That being said I think it is fine this way for now.

2017-01-26 13:23 UTC, tolbertam approved these changes
👍

2017-01-26 14:02 UTC, adutra commented on driver-core/src/test/java/com/datastax/driver/core/CCMBridge.java
> +            return dse || version.compareTo(VersionNumber.parse("4.0")) < 0;
I'm just assuming that all versions of DSE support thrift for now, because I don't know when C* 4.0 will get pulled in DSE.

2017-02-07 19:15 UTC, olim7t commented
> Redesign CassandraVersion and DseVersion to be able to fully accept tick-tock releases and correctly compare them.

💯  for using a string for the version.

2017-02-07 19:28 UTC, merged