Small fixes & improvements in documentation
apache/cassandra-java-driver pull request #934
Opened 2018-01-15 14:32 UTC by alexott

I split changes into separate commits, so they could be applied separately if necessary.

2018-01-16 10:15 UTC, adutra requested changes

2018-01-16 10:15 UTC, adutra commented on manual/ssl/README.md
> +results, use version 4.0.47.Final.
2.0.1 was correct. This artifact does not follow the global Netty versioning scheme.

2018-01-16 10:23 UTC, alexott commented
I reverted corresponding commit...

2018-01-17 11:31 UTC, adutra approved these changes

2018-01-17 11:32 UTC, merged